version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.4 # Sử dụng image PostGIS chính thức
    container_name: car_park_db
    environment:
      - POSTGRES_USER=admin
      #- POSTGRES_PASSWORD=password # Sử dụng biến môi trường hoặc Docker secrets trong thực tế
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=car_parks
    ports:
      - "5432:5432" # Ánh xạ cổng để kết nối từ bên ngoài nếu cần
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local